// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:sangfor_vpn_client/zju_connect.dart')
library;

import 'dart:ffi' as ffi;

/// zcNew creates a session from a JSON configuration (see binding.Config).
///
/// The callbacks may be NULL. user_data is passed back verbatim.
///
/// Returns 0 on failure; when err_out is non-NULL it receives a message that
/// must be freed with zcFreeString.
@ffi.Native<
  zc_client Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Void>,
    zc_event_fn,
    zc_challenge_fn,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>()
external int zcNew(
  ffi.Pointer<ffi.Char> config_json,
  ffi.Pointer<ffi.Void> user_data,
  zc_event_fn on_event,
  zc_challenge_fn on_challenge,
  ffi.Pointer<ffi.Pointer<ffi.Char>> err_out,
);

/// zcSetup performs the VPN login. Returns ZC_OK or a negative code. Blocks.
@ffi.Native<ffi.Int Function(zc_client)>()
external int zcSetup(int client);

/// zcClose tears the session down. Safe to call multiple times.
@ffi.Native<ffi.Void Function(zc_client)>()
external void zcClose(int client);

/// zcFree releases the handle. Call after zcClose.
@ffi.Native<ffi.Void Function(zc_client)>()
external void zcFree(int client);

/// zcStatJSON returns {"state","virtual_ip","session_id","client_data"}.
/// Free the result with zcFreeString.
@ffi.Native<ffi.Pointer<ffi.Char> Function(zc_client)>()
external ffi.Pointer<ffi.Char> zcStatJSON(int client);

/// zcStartProxy starts the local proxies from a JSON ProxyConfig and returns
/// {"socks","http"} with the bound addresses. Free with zcFreeString.
@ffi.Native<ffi.Pointer<ffi.Char> Function(zc_client, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> zcStartProxy(
  int client,
  ffi.Pointer<ffi.Char> proxy_config_json,
);

/// zcReadPacket reads one IPv4 packet into buf. Returns the byte count or a
/// negative code (ZC_ERR_TIMEOUT, ZC_ERR_CLOSED, ...). Blocks up to timeout_ms;
/// zero means forever.
@ffi.Native<
  ffi.Int Function(zc_client, ffi.Pointer<ffi.Uint8>, ffi.Int, ffi.Int)
>()
external int zcReadPacket(
  int client,
  ffi.Pointer<ffi.Uint8> buf,
  int length,
  int timeout_ms,
);

/// zcWritePacket sends one IPv4 packet. Returns ZC_OK or a negative code.
@ffi.Native<ffi.Int Function(zc_client, ffi.Pointer<ffi.Uint8>, ffi.Int)>()
external int zcWritePacket(int client, ffi.Pointer<ffi.Uint8> buf, int length);

/// zcRespondChallenge answers a challenge. response_json is a JSON object.
/// Returns ZC_OK or ZC_ERR_INVALID when the id is unknown.
@ffi.Native<ffi.Int Function(zc_client, ffi.Int64, ffi.Pointer<ffi.Char>)>()
external int zcRespondChallenge(
  int client,
  int challenge_id,
  ffi.Pointer<ffi.Char> response_json,
);

/// zcFreeString frees a string returned by this library. NULL is ignored.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void zcFreeString(ffi.Pointer<ffi.Char> str);

/// zc_client is an opaque session handle. Zero is never valid.
typedef zc_client = ffi.UintPtr;
typedef Dartzc_client = int;
typedef zc_event_fnFunction = ffi.Void Function(
  ffi.Pointer<ffi.Void> user_data,
  ffi.Int type,
  ffi.Pointer<ffi.Char> message,
);
typedef Dartzc_event_fnFunction = void Function(
  ffi.Pointer<ffi.Void> user_data,
  int type,
  ffi.Pointer<ffi.Char> message,
);

/// zc_event_fn receives asynchronous events (logs, state changes, errors).
///
/// message is UTF-8 and only valid for the duration of the call.
typedef zc_event_fn = ffi.Pointer<ffi.NativeFunction<zc_event_fnFunction>>;
typedef zc_challenge_fnFunction = ffi.Void Function(
  ffi.Pointer<ffi.Void> user_data,
  ffi.Int64 challenge_id,
  ffi.Pointer<ffi.Char> payload,
);
typedef Dartzc_challenge_fnFunction = void Function(
  ffi.Pointer<ffi.Void> user_data,
  int challenge_id,
  ffi.Pointer<ffi.Char> payload,
);

/// zc_challenge_fn receives an authentication challenge. The host must answer it
/// with zcRespondChallenge using the same challenge_id. payload is a JSON object
/// whose schema depends on the challenge kind.
typedef zc_challenge_fn =
    ffi.Pointer<ffi.NativeFunction<zc_challenge_fnFunction>>;

const int ZC_EVENT_LOG = 0;

const int ZC_EVENT_STATE = 1;

const int ZC_EVENT_ERROR = 2;

const int ZC_OK = 0;

const int ZC_ERR_INVALID = -1;

const int ZC_ERR_TIMEOUT = -2;

const int ZC_ERR_CLOSED = -3;

const int ZC_ERR_INTERNAL = -4;
